import Head from 'next/head'

import Header, { HeaderTypes } from '@/components/Header'
import Backlog from '@/components/Sections/Backlog'
import { Task } from '@/components/Task/types'
import StepSection from '@/components/Sections/StepSection'

const tasks: Task[] = [
    {
        id: '1',
        title: 'Make Kanban App',
        position: 'backlog',
        status: 'doing',
        developer: 'Kenny'
    },
    {
        id: '2',
        title: 'Make VR Demo app',
        details: 'Hub with links to all working VR demos',
        position: 'backlog',
        status: 'doing',
        developer: 'Kenny'
    }
]

export default function Home() {
    const headerData: HeaderTypes = {
        title: 'Kenny Stanley',
        subtitle: 'Kanban Board',
    }

    return (
        <div className="flex flex-col items-center justify-center">
            <Head>
                <title>Cool as a Kanban</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center justify-start w-full flex-1 px-20 text-center h-screen min-h-screen">
                <Header {...headerData} />
                <section className="flex items-stretch justify-around my-6 sm:w-full gap-2 h-full">
                    <Backlog tasks={tasks} />
                    <StepSection title="Breakdown" />
                    <StepSection title="Implement" />
                    <StepSection title="Verify" />
                </section>
            </main>
        </div>
    )
}
